### ISSUE TITLE
Back end parent issue

### ISSUE THREAD

**Issue by galorin** [galorin/MechCommander2HD#4]
This is the parent issue for all back
end changes

**Comment by galorin** [comment]
I believe that originally MC2 was coded prior to the ratification of the C++98 standard. For ease of programming, I believe that we should, from here on out, code to C++11 and give consideration to using boost.

**Comment by galorin** [comment]
http://www.jarchitect.com/Blog/?p=1566

I will try to use cppdepend to convert the code base to the c++11 and recompile. See what happens. This will tie in with the x64 move as well.

**Comment by HomelessBill** [comment]
x64 isn't going to happen because we don't have the source to GameOS.lib
