### ISSUE TITLE
Update API to DX9

### ISSUE THREAD

**Issue by galorin** [galorin/MechCommander2HD#6]
#1 Graphics

MC2 was written for DirectX 8.  A good first step will be to move to DX9.

As a reference, please see

https://msdn.microsoft.com/en-us/library/windows/desktop/bb204851(v=vs.85).aspx

#7 Get rid of fixed function pipeline
#8 Write shaders

**Comment by HomelessBill** [comment]
We've got a working TODO list, and having way-off future features is just going to clutter things up. If it's not a bug, it's getting closed.
